#!/usr/bin/env bash
stow -v -t ~/ .
if [ ! -h "$HOME/Library/Application Support/Claude/claude_desktop_config.json" ]; then
  ln -s "$PWD/claude_desktop_config.json" "$HOME/Library/Application Support/Claude/claude_desktop_config.json"
fi
