[env]
TERM = "xterm-256color"

[font]
normal = { family = "SauceCodePro Nerd Font" }
size = 13.5

[window]
decorations = "none"
option_as_alt = "both"

[scrolling]
multiplier = 2

[general]
import = ["~/.config/alacritty/catppuccin-frappe.toml"]
